### ISSUE TITLE
Resource Leak

### ISSUE THREAD

**Issue by jeroenvollenbrock** [FlupkeZwe/com.entone.ir#1]
The following code registers a new entone500 signal instance for every command that is sent. 
 https://github.com/FlupkeZwe/com.entone.ir/blob/7a4a64cc1f320aa32edbe370b0539861ce12f8c0/drivers/entone_remote/device.js#L32 

There should only be one signal instance of each signal at any given time, and this behaviour will start throwing errors in the near future. It's better to create & register the signal in the driver [`onInit`](https://developer.athom.com/docs/apps/Driver.html#onInit), set it on the driver instance (eg `this._entoneSignal = ....`, add a `performCommand` function to `driver.js` that just invokes `entoneSignal.cmd()`, and invoke this using `this.getDriver().performCommand()` in place of the current implementation of the `_performCommand` function.

**Comment by FlupkeZwe** [comment]
Hi Jeroen,

Pull requests are appreciated.

Best regards
Frits

Op di 13 nov. 2018 13:31 schreef Jeroen Vollenbrock <
notifications@github.com:

**Comment by FlupkeZwe** [comment]
Resolved in 1.0.2.
